version: "3.7"

services:
  api:
    container_name: victo-api
    build:
      context: ../..
      dockerfile: ./scripts/docker/Dockerfile
    volumes:
      - ../..:/var/www/
    tty: true
    ports:
      - "3001:3001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - victo_network

  db:
    container_name: victo-db
    image: mysql:8.0
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - victo_network

volumes:
  db_data:

networks:
  victo_network:
    external: true
