version: "3.7"

services:
  api:
    image: tmp-friends/victo-api:latest
    container_name: victo-api
    volumes:
      - ../..:/var/www/
    tty: true
    ports:
      - "3001:3001"
    networks:
      - victo_network

networks:
  victo_network:
    external: true
