CREATE TABLE IF NOT EXISTS hashtag (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT "id",
  tagName VARCHAR(191) NOT NULL COMMENT "tag name",
  isSelf TINYINT(1) NOT NULL DEFAULT 1 COMMENT "is self",
  PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
