CREATE TABLE IF NOT EXISTS media (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT "id",
  tweetId INT(11) NOT NULL COMMENT "tweet id",
  type VARCHAR(191) NOT NULL COMMENT "type",
  url VARCHAR(191) NOT NULL COMMENT "url",
  PRIMARY KEY (id),
  FOREIGN KEY(tweetId) REFERENCES tweet(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
