// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	HashtagFollows   string
	Hashtags         string
	MediaObjects     string
	SchemaMigrations string
	TweetObjects     string
	Users            string
	Vtubers          string
}{
	HashtagFollows:   "hashtag_follows",
	Hashtags:         "hashtags",
	MediaObjects:     "media_objects",
	SchemaMigrations: "schema_migrations",
	TweetObjects:     "tweet_objects",
	Users:            "users",
	Vtubers:          "vtubers",
}
